"""Polymarket CLOB V2 order entry, offline.

Two kinds of evidence, kept apart.

* **Signing** is checked against `tests/samples/polymarket_signing_vectors.json`,
  generated by the venue's own `py-clob-client-v2` (1.1.0) for the public
  Hardhat test key: every order signature and hash for all four wallet types
  on both exchanges, the L1 auth signature, the L2 HMAC and 1,140 limit-order
  amount cases. These must match byte for byte.
* **Responses** are the shapes in the venue's documentation and OpenAPI
  (`clob-openapi.yaml`, Data API v2). No Polymarket account can be opened
  from the UK, so none were captured live; the fixtures below are the
  documented examples, with addresses replaced by test values.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
from decimal import Decimal
from pathlib import Path

import httpx
import pytest
from eth_account import Account as EthAccount
from eth_account.messages import encode_typed_data

from synpath.errors import NotSupported
from synpath.trading import OrderRequest, OrderStatus, OrderType, Side, TimeInForce
from synpath.trading import polymarket_signing as sig
from synpath.trading.credentials import SYNPATH_BUILDER_CODE, PolymarketCredentials, load_polymarket
from synpath.trading.errors import CredentialsMissing, InsufficientFunds, InvalidOrder, MarketHalted, OrderNotFound, OrderRejected
from synpath.trading.limiter import BudgetLimiter
from synpath.trading.polymarket import (
    GTD_SAFETY_S, MarketTokens, PolymarketTrading, TokenInfo, build_signed_order, error_of, fills_of, order_of,
    position_of, serialize, wire_leg,
)
from synpath.trading.types import Liquidity, PositionSide, SettlementState

D = Decimal
pytestmark = pytest.mark.anyio
VECTORS = json.loads((Path(__file__).parent / "samples" / "polymarket_signing_vectors.json").read_text())
KEY = VECTORS["private_key"]
ADDRESS = VECTORS["address"]
WALLET = "0x1111111111111111111111111111111111111111"
TOKEN = "71321045679252212594626385532706912750332728571942532289631379312455583992563"
CONDITION = "0x747dc809fb79e1b05be09c42d6179459a58de2ef3e40f02484a4e1260f741f75"
NO_TOKEN = "2"
GAMMA_ID = "1"
MARKET = f"polymarket:{GAMMA_ID}"
GAMMA_ROW = {"id": GAMMA_ID, "conditionId": CONDITION, "clobTokenIds": f'["{TOKEN}", "{NO_TOKEN}"]', "negRisk": False}
TOKENS = MarketTokens.from_gamma(GAMMA_ROW)


def outcome_of(token_id: str) -> str:
    return TOKENS.outcome_of(token_id)
SECRET = base64.urlsafe_b64encode(b"a test secret that is not real!!").decode()


@pytest.fixture
def anyio_backend():
    return "asyncio"


def creds(**kw) -> PolymarketCredentials:
    base = dict(private_key=KEY, signature_type=3, funder=WALLET, api_key="api-key-uuid",
                api_secret=SECRET, api_passphrase="pass")
    base.update(kw)
    return PolymarketCredentials(**base)


def token(**kw) -> TokenInfo:
    base = dict(token_id=TOKEN, condition_id=CONDITION, tick=D("0.01"), min_size=D("5"), neg_risk=False)
    base.update(kw)
    return TokenInfo(**base)


def req(**kw) -> OrderRequest:
    base = dict(market_id=MARKET, side=Side.BUY, amount=D("10"), price=D("0.52"))
    base.update(kw)
    return OrderRequest(**base)


# ---------------------------------------------------------------------------
# Signing, against the venue's client
# ---------------------------------------------------------------------------

class TestSigningVectors:
    signer = sig.WalletSigner(KEY)

    def test_signer_address(self):
        assert self.signer.address == ADDRESS

    @pytest.mark.parametrize("vector", VECTORS["orders"], ids=lambda v: f"type{v['signature_type']}-{'negrisk' if v['neg_risk'] else 'std'}-{v['side']}")
    def test_order_signature_and_hash(self, vector):
        order = sig.build_order(
            maker=vector["maker"], signer=vector["signer"], token_id=vector["token_id"],
            maker_amount=vector["maker_amount"], taker_amount=vector["taker_amount"], side=vector["side"],
            signature_type=vector["signature_type"], timestamp_ms=vector["timestamp"], salt=vector["salt"],
            expiration=int(vector["expiration"]), builder=vector["builder"],
        )
        assert sig.sign_order(self.signer, order, neg_risk=vector["neg_risk"]) == vector["signature"]
        assert sig.order_hash(order, neg_risk=vector["neg_risk"]) == vector["hash"]

    def test_every_limit_amount_case(self):
        mismatched = [
            case for case in VECTORS["amounts"]
            if sig.limit_amounts(case["side"], D(case["price"]), D(case["size"]), D(case["tick"])) != (case["maker"], case["taker"])
        ]
        assert len(VECTORS["amounts"]) == 1140
        assert mismatched == []

    @pytest.mark.parametrize("vector", VECTORS["l1"])
    def test_l1_signature(self, vector):
        headers = sig.l1_headers(self.signer, vector["timestamp"], vector["nonce"])
        assert headers["POLY_SIGNATURE"] == vector["signature"]
        assert headers["POLY_ADDRESS"] == ADDRESS and headers["POLY_NONCE"] == str(vector["nonce"])

    @pytest.mark.parametrize("vector", VECTORS["hmac"])
    def test_l2_hmac(self, vector):
        assert sig.l2_signature(vector["secret"], vector["timestamp"], vector["method"], vector["path"], vector["body"]) == vector["signature"]

    def test_the_documented_buy_example(self):
        # The venue's own worked example: BUY 10 at 0.52 -> 5200000 / 10000000.
        assert sig.limit_amounts("BUY", D("0.52"), D("10"), D("0.01")) == (5_200_000, 10_000_000)
        assert sig.limit_amounts("SELL", D("0.52"), D("10"), D("0.01")) == (10_000_000, 5_200_000)

    def test_unknown_tick_is_refused(self):
        with pytest.raises(InvalidOrder, match="precision"):
            sig.limit_amounts("BUY", D("0.5"), D("10"), D("0.02"))


class TestWalletCalls:
    def test_selectors_are_the_conditional_tokens_ones(self):
        # Published selectors of ERC-20, ERC-1155 and the Gnosis CTF.
        assert sig.approve_calldata(sig.EXCHANGE).startswith("0x095ea7b3")
        assert sig.set_approval_for_all_calldata(sig.EXCHANGE).startswith("0xa22cb465")
        assert sig.split_calldata(CONDITION, 1).startswith("0x72ce4275")
        assert sig.merge_calldata(CONDITION, 1).startswith("0x9e7212ad")
        assert sig.redeem_calldata(CONDITION).startswith("0x01b7037c")

    def test_split_encodes_pusd_condition_partition_and_amount(self):
        from eth_abi import decode
        data = bytes.fromhex(sig.split_calldata(CONDITION, 5_000_000)[10:])
        collateral, parent, condition, partition, amount = decode(["address", "bytes32", "bytes32", "uint256[]", "uint256"], data)
        assert collateral.lower() == sig.PUSD.lower() and parent == b"\x00" * 32
        assert "0x" + condition.hex() == CONDITION and list(partition) == [1, 2] and amount == 5_000_000

    def test_bad_condition_id(self):
        with pytest.raises(InvalidOrder, match="condition id"):
            sig.redeem_calldata("0x1234")

    def test_approval_calls_cover_each_spender_for_both_tokens(self):
        calls = sig.trading_approval_calls([sig.EXCHANGE, sig.NEG_RISK_EXCHANGE])
        assert [c["target"] for c in calls] == [sig.PUSD, sig.PUSD, sig.CONDITIONAL_TOKENS, sig.CONDITIONAL_TOKENS]
        assert sig.NEG_RISK_EXCHANGE[2:].lower() in calls[1]["data"].lower()
        assert len(sig.trading_approval_calls()) == 8

    def test_wallet_batch_signature_recovers_to_the_signer(self):
        signer = sig.WalletSigner(KEY)
        calls = sig.trading_approval_calls([sig.EXCHANGE])
        typed = sig.wallet_batch_typed_data(WALLET, 7, 1_800_000_000, calls)
        signature = signer.sign_typed_data(typed)
        assert EthAccount.recover_message(encode_typed_data(full_message=typed), signature=signature) == ADDRESS
        assert typed["domain"]["verifyingContract"] == WALLET and typed["domain"]["name"] == "DepositWallet"

    def test_deposit_wallet_wrap_layout(self):
        signer = sig.WalletSigner(KEY)
        order = sig.build_order(maker=WALLET, signer=WALLET, token_id=TOKEN, maker_amount=1, taker_amount=2,
                                side="BUY", signature_type=3, timestamp_ms=1, salt=1)
        raw = bytes.fromhex(sig.sign_order(signer, order, neg_risk=False)[2:])
        type_bytes = sig.ORDER_TYPE.encode()
        assert int.from_bytes(raw[-2:], "big") == len(type_bytes)
        assert raw[-2 - len(type_bytes):-2] == type_bytes
        assert len(raw) == 65 + 32 + 32 + len(type_bytes) + 2


# ---------------------------------------------------------------------------
# Order translation
# ---------------------------------------------------------------------------

def build(request: OrderRequest, *, info: TokenInfo | None = None, **creds_kw):
    return build_signed_order(
        request, info or token(), signer=sig.WalletSigner(KEY), creds=creds(**creds_kw),
        api_key="api-key-uuid", now_ms=1_789_650_000_000, salt=479249096354,
    )


class TestTranslate:
    def test_gtc_buy_on_a_deposit_wallet(self):
        entry, order_id = build(req())
        order = entry["order"]
        assert entry["orderType"] == "GTC" and entry["owner"] == "api-key-uuid" and entry["deferExec"] is False
        assert "postOnly" not in entry
        assert order["side"] == "BUY" and order["tokenId"] == TOKEN
        assert (order["makerAmount"], order["takerAmount"]) == ("5200000", "10000000")
        assert order["maker"] == WALLET and order["signer"] == WALLET and order["signatureType"] == 3
        assert order["expiration"] == "0" and order["timestamp"] == "1789650000000"
        assert order["builder"] == SYNPATH_BUILDER_CODE, "Synpath's builder code by default"
        assert order_id == sig.order_hash(order, neg_risk=False)

    @pytest.mark.parametrize("kind,maker,signer", [(0, ADDRESS, ADDRESS), (1, WALLET, ADDRESS), (2, WALLET, ADDRESS), (3, WALLET, WALLET)])
    def test_maker_and_signer_per_wallet_type(self, kind, maker, signer):
        entry, _ = build(req(), signature_type=kind, funder=None if kind == 0 else WALLET)
        assert entry["order"]["maker"] == maker and entry["order"]["signer"] == signer
        assert entry["order"]["signatureType"] == kind

    def test_neg_risk_signs_for_the_neg_risk_exchange(self):
        entry, order_id = build(req(), info=token(neg_risk=True))
        assert order_id == sig.order_hash(entry["order"], neg_risk=True) != sig.order_hash(entry["order"], neg_risk=False)

    @pytest.mark.parametrize("tif,wire", [(TimeInForce.GTC, "GTC"), (TimeInForce.IOC, "FAK"), (TimeInForce.FOK, "FOK")])
    def test_time_in_force(self, tif, wire):
        assert build(req(time_in_force=tif))[0]["orderType"] == wire

    def test_gtd_adds_the_venue_minute(self):
        expires = 1_789_650_000_000 + 3_600_000
        entry, _ = build(req(time_in_force=TimeInForce.GTD, expires_at=expires))
        assert entry["orderType"] == "GTD"
        assert int(entry["order"]["expiration"]) == expires // 1000 + GTD_SAFETY_S

    def test_gtd_too_soon_is_refused(self):
        with pytest.raises(InvalidOrder, match="at least 120s"):
            build(req(time_in_force=TimeInForce.GTD, expires_at=1_789_650_000_000 + 60_000))

    def test_market_is_an_immediate_limit(self):
        assert build(req(type=OrderType.MARKET))[0]["orderType"] == "FAK"
        assert build(req(type=OrderType.MARKET, time_in_force=TimeInForce.FOK))[0]["orderType"] == "FOK"
        with pytest.raises(InvalidOrder, match="protection price"):
            build(req(type=OrderType.MARKET, price=None))

    def test_post_only(self):
        assert build(req(post_only=True))[0]["postOnly"] is True
        with pytest.raises(InvalidOrder, match="gtc or gtd"):
            build(req(post_only=True, time_in_force=TimeInForce.IOC))

    @pytest.mark.parametrize("kw,match", [
        ({"price": D("0.525")}, "tick"),
        ({"price": D("0.995"), "amount": D("10")}, "tick"),
        ({"amount": D("4.99")}, "minimum"),
        ({"amount": D("10.005")}, "multiple"),
        ({"time_in_force": TimeInForce.DAY}, "engine"),
        ({"type": OrderType.STOP_LIMIT, "stop_price": D("0.4")}, "execution engine"),
        ({"market_id": "kalshi:T"}, "belongs to kalshi"),
    ])
    def test_refused_before_signing(self, kw, match):
        with pytest.raises(InvalidOrder, match=match):
            build(req(**kw))

    def test_a_finer_tick_allows_finer_prices(self):
        with pytest.raises(InvalidOrder, match="tick"):
            build(req(price=D("0.001")), info=token(tick=D("0.01")))
        assert build(req(price=D("0.001"), amount=D("5000")), info=token(tick=D("0.001")))[0]["order"]["makerAmount"] == "5000000"

    def test_builder_code_is_signed_into_the_order(self):
        code = "0x" + "ab" * 32
        entry, order_id = build(req(), builder_code=code)
        assert entry["order"]["builder"] == code
        assert order_id != build(req())[1]

    def test_serialization_is_compact_and_stable(self):
        assert serialize({"b": 1, "a": [1, "x"]}) == '{"b":1,"a":[1,"x"]}'


# ---------------------------------------------------------------------------
# Normalizers, on documented shapes
# ---------------------------------------------------------------------------

DOC_ORDER = {
    "id": "0xorder", "market": CONDITION, "asset_id": TOKEN, "owner": "api-key-uuid", "maker_address": WALLET,
    "side": "BUY", "price": "0.52", "original_size": "10", "size_matched": "0", "outcome": "Yes",
    "order_type": "GTC", "status": "LIVE", "associate_trades": [], "created_at": 1748779200, "expiration": "0",
}

DOC_TRADE_TAKER = {
    "id": "TRADE_ID", "market": CONDITION, "asset_id": TOKEN, "owner": "api-key-uuid", "maker_address": WALLET,
    "taker_order_id": "0xorder", "side": "BUY", "trader_side": "TAKER", "price": "0.52", "size": "10",
    "outcome": "Yes", "status": "MATCHED", "fee_rate_bps": "0", "bucket_index": 0, "transaction_hash": "0xabc",
    "maker_orders": [], "match_time": "1748779205", "last_update": "1748779205",
}

DOC_TRADE_MAKER = {
    **DOC_TRADE_TAKER, "trader_side": "MAKER", "status": "TRADE_STATUS_CONFIRMED", "owner": "someone-else",
    "maker_orders": [
        {"order_id": "0xmine", "owner": "api-key-uuid", "maker_address": WALLET, "matched_amount": "4",
         "price": "0.52", "fee_rate_bps": "0", "asset_id": TOKEN, "outcome": "Yes", "side": "SELL"},
        {"order_id": "0xtheirs", "owner": "other", "maker_address": "0x2222222222222222222222222222222222222222",
         "matched_amount": "6", "price": "0.52", "fee_rate_bps": "0", "asset_id": TOKEN, "outcome": "Yes", "side": "SELL"},
    ],
}

DOC_POSITION = {
    "proxy_wallet": WALLET, "token_id": TOKEN, "condition_id": CONDITION, "current_size": 76.72, "avg_price": 0.41,
    "entry_cost_usdc": 31.45, "current_price": 0.52, "current_value": 39.89, "total_size": 76.72,
    "realized_pnl": 0.0, "unrealized_pnl": 8.44, "status": "OPEN", "redeemable": False, "mergeable": False,
    "negative_risk": False, "outcome": "Yes", "outcome_index": 0, "last_event_at": 1789650000,
}


class TestLegs:
    """One rule for the four intents: buy takes YES, sell takes NO, and
    reduce_only turns either into selling the tokens held."""

    @pytest.mark.parametrize("side,reduce_only,outcome,venue_side,wire_price", [
        (Side.BUY, False, "yes", "BUY", "0.52"),
        (Side.SELL, False, "no", "BUY", "0.48"),
        (Side.SELL, True, "yes", "SELL", "0.52"),
        (Side.BUY, True, "no", "SELL", "0.48"),
    ])
    def test_wire_leg_and_price(self, side, reduce_only, outcome, venue_side, wire_price):
        request = req(side=side, reduce_only=reduce_only)
        assert wire_leg(request) == (outcome, venue_side)
        info = token(token_id=TOKENS.token(outcome))
        entry, _ = build(request, info=info)
        order = entry["order"]
        assert order["tokenId"] == TOKENS.token(outcome) and order["side"] == venue_side
        maker, taker = int(order["makerAmount"]), int(order["takerAmount"])
        price = D(maker) / D(taker) if venue_side == "BUY" else D(taker) / D(maker)
        assert price == D(wire_price)


class TestNormalizers:
    def test_live_order(self):
        order = order_of(DOC_ORDER, market_id=MARKET, outcome="yes")
        assert order.id == "0xorder" and order.market_id == MARKET
        assert order.status == OrderStatus.OPEN and order.side == Side.BUY and order.price == D("0.52")
        assert order.amount == D("10") and order.filled == 0 and order.remaining == D("10")
        assert order.time_in_force == TimeInForce.GTC and order.expires_at is None
        assert order.created_at == 1748779200000

    @pytest.mark.parametrize("status,expected", [
        ("MATCHED", OrderStatus.CLOSED), ("CANCELED", OrderStatus.CANCELED),
        ("CANCELED_MARKET_RESOLVED", OrderStatus.CANCELED), ("INVALID", OrderStatus.REJECTED), ("live", OrderStatus.OPEN),
    ])
    def test_status_words(self, status, expected):
        size = {"size_matched": "10"} if status == "MATCHED" else {}
        assert order_of({**DOC_ORDER, "status": status, **size}, market_id=MARKET, outcome="yes").status == expected

    def test_partly_matched_order_still_resting_is_open(self):
        order = order_of({**DOC_ORDER, "status": "MATCHED", "size_matched": "4"}, market_id=MARKET, outcome="yes")
        assert order.status == OrderStatus.OPEN and order.filled == D("4") and order.remaining == D("6")

    def test_gtd_expiry_is_the_effective_one(self):
        order = order_of({**DOC_ORDER, "order_type": "GTD", "expiration": "1789653660"}, market_id=MARKET, outcome="yes")
        assert order.time_in_force == TimeInForce.GTD and order.expires_at == (1789653660 - 60) * 1000

    def test_an_order_on_the_no_token_reads_back_on_the_yes_leg(self):
        order = order_of({**DOC_ORDER, "asset_id": NO_TOKEN, "side": "BUY", "price": "0.30"}, market_id=MARKET, outcome="no")
        assert order.side == Side.SELL and order.price == D("0.70")

    def test_taker_fill(self):
        (fill,) = fills_of(DOC_TRADE_TAKER, api_key="api-key-uuid", wallets={WALLET}, market_id=MARKET, outcome_of=outcome_of)
        assert fill.id == "TRADE_ID" and fill.order_id == "0xorder" and fill.liquidity == Liquidity.TAKER
        assert fill.side == Side.BUY and fill.amount == D("10") and fill.price == D("0.52")
        assert fill.settlement == SettlementState.MATCHED and fill.timestamp == 1748779205000

    def test_maker_fill_takes_only_our_legs(self):
        (fill,) = fills_of(DOC_TRADE_MAKER, api_key="api-key-uuid", wallets={WALLET}, market_id=MARKET, outcome_of=outcome_of)
        assert fill.order_id == "0xmine" and fill.id == "TRADE_ID:0xmine"
        assert fill.amount == D("4") and fill.side == Side.SELL and fill.liquidity == Liquidity.MAKER
        assert fill.settlement == SettlementState.CONFIRMED and fill.fee == 0

    @pytest.mark.parametrize("status,state", [("MINED", SettlementState.MATCHED), ("RETRYING", SettlementState.MATCHED), ("FAILED", SettlementState.FAILED)])
    def test_settlement_states(self, status, state):
        (fill,) = fills_of({**DOC_TRADE_TAKER, "status": status}, api_key="k", wallets=set(), market_id=MARKET, outcome_of=outcome_of)
        assert fill.settlement == state

    def test_position_nets_the_two_inventories(self):
        pos = position_of([DOC_POSITION], market_id=MARKET, outcome_of=outcome_of)
        assert pos.market_id == MARKET and pos.side == PositionSide.LONG
        assert pos.contracts == pos.inventory_yes == D("76.72") and pos.inventory_no == 0
        assert pos.entry_price == D("0.41") and pos.mark_price == D("0.52") and pos.unrealized_pnl == D("8.44")
        assert not pos.resolved and pos.redeemable is None and pos.timestamp == 1789650000000

    def test_a_no_inventory_is_a_short_on_the_yes_leg(self):
        no_row = {**DOC_POSITION, "token_id": NO_TOKEN, "current_size": 10, "avg_price": 0.30, "current_price": 0.48}
        pos = position_of([DOC_POSITION, no_row], market_id=MARKET, outcome_of=outcome_of)
        assert pos.side == PositionSide.LONG and pos.contracts == D("66.72")
        assert pos.inventory_yes == D("76.72") and pos.inventory_no == D("10")
        only_no = position_of([no_row], market_id=MARKET, outcome_of=outcome_of)
        assert only_no.side == PositionSide.SHORT and only_no.contracts == D("10")
        assert only_no.entry_price == D("0.70") and only_no.mark_price == D("0.52")

    def test_redeemable_position(self):
        pos = position_of([{**DOC_POSITION, "status": "REDEEMABLE", "redeemable": True, "current_value": 76.72}], market_id=MARKET, outcome_of=outcome_of)
        assert pos.resolved and pos.redeemable == D("76.72") and pos.final is False

    @pytest.mark.parametrize("message,kind,reason", [
        ("not enough balance / allowance", InsufficientFunds, None),
        ("order 0x1 is invalid. Price (0.525) breaks minimum tick size rule: 0.01", InvalidOrder, None),
        ("order 0x1 is invalid. Size (1) lower than the minimum: 5", InvalidOrder, None),
        ("Trading is currently cancel-only. New orders are not accepted, but cancels are allowed.", MarketHalted, None),
        ("post-only mode: only post-only orders and cancels are allowed", MarketHalted, None),
        ("invalid post-only order: order crosses book", OrderRejected, "post_only_would_cross"),
        ("order couldn't be fully filled. FOK orders are fully filled or killed.", OrderRejected, "fok_not_filled"),
        ("no orders found to match with FAK order. FAK orders are partially filled or killed if no match is found.", OrderRejected, "fak_no_match"),
        ("order 0x1 is invalid. Duplicated.", OrderRejected, "duplicate"),
    ])
    def test_documented_errors(self, message, kind, reason):
        err = error_of(message)
        assert isinstance(err, kind)
        if reason:
            assert err.reason == reason


# ---------------------------------------------------------------------------
# Adapter, over a mock transport
# ---------------------------------------------------------------------------

class Venue:
    """Scripted responses by (method, path); records every request."""

    def __init__(self):
        self.requests: list[httpx.Request] = []
        self.routes: dict[tuple[str, str], list[tuple[int, object]]] = {}

    def on(self, method: str, path: str, status: int = 200, body: object = None):
        self.routes.setdefault((method, path), []).append((status, body))

    def handler(self, request: httpx.Request) -> httpx.Response:
        self.requests.append(request)
        key = (request.method, request.url.path)
        queue = self.routes.get(key) or []
        if not queue:
            return httpx.Response(599, json={"error": f"no route for {key}"})
        status, body = queue.pop(0) if len(queue) > 1 else queue[0]
        return httpx.Response(status, json=body) if body is not None else httpx.Response(status)

    def client(self) -> httpx.AsyncClient:
        return httpx.AsyncClient(transport=httpx.MockTransport(self.handler))

    def sent(self, method: str, path: str) -> list[httpx.Request]:
        return [r for r in self.requests if r.method == method and r.url.path == path]


BOOK = {"market": CONDITION, "asset_id": TOKEN, "bids": [], "asks": [], "tick_size": "0.01", "min_order_size": "5", "neg_risk": False}


@pytest.fixture
def venue():
    v = Venue()
    v.on("GET", "/book", body=BOOK)
    # The Gamma catalog, on the same mock transport: which token is which side.
    v.on("GET", f"/markets/{GAMMA_ID}", body=GAMMA_ROW)
    v.on("GET", "/markets", body=[GAMMA_ROW])
    return v


def adapter(venue: Venue, **kw) -> PolymarketTrading:
    return PolymarketTrading(creds(**kw), client=venue.client(), limiter=BudgetLimiter(read_per_second=1000, write_per_second=1000))


def check_hmac(request: httpx.Request, path: str):
    stamp = request.headers["POLY_TIMESTAMP"]
    body = request.content.decode() if request.content else ""
    expected = base64.urlsafe_b64encode(hmac.new(base64.urlsafe_b64decode(SECRET), f"{stamp}{request.method}{path}{body}".encode(), hashlib.sha256).digest()).decode()
    assert request.headers["POLY_SIGNATURE"] == expected
    assert request.headers["POLY_API_KEY"] == "api-key-uuid" and request.headers["POLY_PASSPHRASE"] == "pass"
    assert request.headers["POLY_ADDRESS"] == ADDRESS


class TestAdapter:
    def test_capabilities(self):
        has = PolymarketTrading.has
        assert has["create_order"] and has["fetch_my_trades"] and has["fetch_positions"]
        assert has["edit_order"] is False and has["fetch_orders"] is False and has["fetch_queue_position"] is False
        assert has["split_merge"] == "partial"
        assert set(has.values()) <= {True, False, "partial"}

    def test_smart_wallet_without_funder_is_refused(self, venue):
        with pytest.raises(CredentialsMissing, match="funder"):
            PolymarketTrading(PolymarketCredentials(private_key=KEY, signature_type=3), client=venue.client())

    async def test_credentials_are_derived_then_created(self, venue):
        venue.on("GET", "/auth/derive-api-key", 400, {"error": "Could not derive api key!"})
        venue.on("POST", "/auth/api-key", body={"apiKey": "new-key", "secret": SECRET, "passphrase": "pp"})
        poly = adapter(venue, api_key=None, api_secret=None, api_passphrase=None)
        assert await poly.ensure_api_credentials() == "new-key"
        derive = venue.sent("GET", "/auth/derive-api-key")[0]
        assert derive.headers["POLY_ADDRESS"] == ADDRESS and derive.headers["POLY_NONCE"] == "0"
        typed = sig.clob_auth_typed_data(ADDRESS, int(derive.headers["POLY_TIMESTAMP"]), 0)
        assert EthAccount.recover_message(encode_typed_data(full_message=typed), signature=derive.headers["POLY_SIGNATURE"]) == ADDRESS
        assert await poly.ensure_api_credentials() == "new-key"  # cached
        assert len(venue.sent("POST", "/auth/api-key")) == 1

    async def test_create_order_sends_the_signed_body_it_hashed(self, venue):
        venue.on("POST", "/order", body={"success": True, "errorMsg": "", "orderID": "", "status": "live",
                                         "makingAmount": "", "takingAmount": "", "transactionsHashes": [], "tradeIDs": []})
        poly = adapter(venue)
        order = await poly.create_order(req(client_order_id="mine-1", book="alpha"))
        sent = venue.sent("POST", "/order")[0]
        check_hmac(sent, "/order")
        body = json.loads(sent.content)
        assert sent.content.decode() == serialize(body)
        assert order.id == sig.order_hash(body["order"], neg_risk=False) == order.info["computed_id"]
        assert order.status == OrderStatus.OPEN and order.amount == D("10") and order.market_id == MARKET
        assert order.client_order_id == "mine-1" and order.book == "alpha"
        # the signature in the body verifies as a deposit-wallet order from this signer
        assert body["order"]["signature"] == sig.sign_order(sig.WalletSigner(KEY), {k: v for k, v in body["order"].items() if k != "signature"}, neg_risk=False)

    async def test_matched_answer_is_pending_until_read_back(self, venue):
        venue.on("POST", "/order", body={"success": True, "errorMsg": "", "orderID": "0xabc", "status": "matched",
                                         "makingAmount": "5200000", "takingAmount": "10000000", "tradeIDs": ["t1"]})
        order = await adapter(venue).create_order(req(time_in_force=TimeInForce.IOC))
        assert order.status == OrderStatus.PENDING and order.id == "0xabc"

    async def test_venue_refusal_in_a_200(self, venue):
        venue.on("POST", "/order", body={"success": False, "errorMsg": "not enough balance / allowance", "orderID": "", "status": ""})
        with pytest.raises(InsufficientFunds):
            await adapter(venue).create_order(req())

    async def test_cancel_only_mode_is_a_halt(self, venue):
        venue.on("POST", "/order", 503, {"error": "Trading is currently cancel-only. New orders are not accepted, but cancels are allowed."})
        with pytest.raises(MarketHalted):
            await adapter(venue).create_order(req())

    async def test_stale_tick_is_forgotten(self, venue):
        venue.on("POST", "/order", 400, {"error": "order 0x1 is invalid. Price (0.52) breaks minimum tick size rule: 0.1"})
        poly = adapter(venue)
        with pytest.raises(InvalidOrder):
            await poly.create_order(req())
        assert TOKEN not in poly._tokens

    async def test_create_orders_batches_by_fifteen(self, venue):
        answer = {"success": True, "errorMsg": "", "orderID": "", "status": "live"}
        venue.on("POST", "/orders", body=[answer] * 15)
        venue.on("POST", "/orders", body=[answer] * 3 + [{"success": False, "errorMsg": "not enough balance / allowance"}])
        requests = [req() for _ in range(19)] + [req(price=D("0.525"))]
        results = await adapter(venue).create_orders(requests)
        batches = venue.sent("POST", "/orders")
        assert [len(json.loads(r.content)) for r in batches] == [15, 4]
        assert isinstance(results[18], InsufficientFunds) and isinstance(results[19], InvalidOrder)
        assert all(r.status == OrderStatus.OPEN for r in results[:18])

    async def test_cancel_reads_back(self, venue):
        venue.on("DELETE", "/order", body={"canceled": ["0xorder"], "not_canceled": {}})
        venue.on("GET", "/data/order/0xorder", body={**DOC_ORDER, "status": "CANCELED", "size_matched": "3"})
        order = await adapter(venue).cancel_order("0xorder")
        sent = venue.sent("DELETE", "/order")[0]
        assert sent.content == b'{"orderID":"0xorder"}'
        check_hmac(sent, "/order")
        assert order.status == OrderStatus.CANCELED and order.filled == D("3") and order.remaining == 0

    async def test_cancel_of_a_matched_order_returns_it(self, venue):
        venue.on("DELETE", "/order", body={"canceled": [], "not_canceled": {"0xorder": "order already matched"}})
        venue.on("GET", "/data/order/0xorder", body={**DOC_ORDER, "status": "MATCHED", "size_matched": "10"})
        order = await adapter(venue).cancel_order("0xorder")
        assert order.status == OrderStatus.CLOSED and order.info["cancel"]["not_canceled"]

    async def test_cancel_refused_on_a_live_order_raises(self, venue):
        venue.on("DELETE", "/order", body={"canceled": [], "not_canceled": {"0xorder": "order is in a delay window"}})
        venue.on("GET", "/data/order/0xorder", body=DOC_ORDER)
        with pytest.raises(OrderRejected, match="delay window"):
            await adapter(venue).cancel_order("0xorder")

    async def test_cancel_orders_reports_each_verdict(self, venue):
        venue.on("DELETE", "/orders", body={"canceled": ["a"], "not_canceled": {"b": "order already matched"}})
        a, b = await adapter(venue).cancel_orders(["a", "b"])
        assert a.status == OrderStatus.CANCELED and isinstance(b, OrderRejected)
        assert json.loads(venue.sent("DELETE", "/orders")[0].content) == ["a", "b"]

    async def test_cancel_all_scopes(self, venue):
        venue.on("DELETE", "/cancel-all", body={"canceled": ["a", "b"], "not_canceled": {}})
        venue.on("DELETE", "/cancel-market-orders", body={"canceled": ["c"], "not_canceled": {}})
        poly = adapter(venue)
        assert await poly.cancel_all_orders() == 2
        assert await poly.cancel_all_orders(market_id=MARKET) == 1
        bodies = [json.loads(r.content) for r in venue.sent("DELETE", "/cancel-market-orders")]
        assert bodies == [{"market": CONDITION}]
        assert venue.sent("DELETE", "/cancel-all")[0].content == b""

    async def test_unknown_order(self, venue):
        venue.on("GET", "/data/order/0xnope", 404, {"error": "not found"})
        with pytest.raises(OrderNotFound):
            await adapter(venue).fetch_order("0xnope")

    async def test_open_orders_walk_to_the_end_cursor(self, venue):
        venue.on("GET", "/data/orders", body={"limit": 1, "next_cursor": "MQ==", "count": 1, "data": [DOC_ORDER]})
        venue.on("GET", "/data/orders", body={"limit": 1, "next_cursor": "LTE=", "count": 1, "data": [{**DOC_ORDER, "id": "0xtwo"}]})
        orders = await adapter(venue).fetch_open_orders(market_id=MARKET)
        assert [o.id for o in orders] == ["0xorder", "0xtwo"] and orders[0].market_id == MARKET
        sent = venue.sent("GET", "/data/orders")
        assert sent[0].url.params["market"] == CONDITION
        assert sent[0].url.params["next_cursor"] == "MA==" and sent[1].url.params["next_cursor"] == "MQ=="
        check_hmac(sent[0], "/data/orders")  # query string is not signed

    async def test_my_trades(self, venue):
        venue.on("GET", "/data/trades", body={"limit": 300, "next_cursor": "LTE=", "count": 2, "data": [DOC_TRADE_TAKER, DOC_TRADE_MAKER]})
        page = await adapter(venue).fetch_my_trades(market_id=MARKET)
        assert [f.liquidity for f in page] == [Liquidity.TAKER, Liquidity.MAKER] and page.next_cursor is None

    async def test_balance_is_six_decimal_pusd(self, venue):
        venue.on("GET", "/balance-allowance", body={"balance": "123456789", "allowances": {sig.EXCHANGE: "0"}})
        balance = await adapter(venue).fetch_balance()
        assert balance.currency == "pUSD" and balance.available == D("123.456789") and balance.locked is None
        assert venue.sent("GET", "/balance-allowance")[0].url.params["signature_type"] == "3"

    async def test_positions_page_through_the_data_api(self, venue):
        venue.on("GET", "/v2/positions", body={"data": [DOC_POSITION], "pagination": {"next_cursor": "abc"}})
        venue.on("GET", "/v2/positions", body={"data": [{**DOC_POSITION, "token_id": NO_TOKEN, "current_size": 0}], "pagination": {"next_cursor": None}})
        positions = await adapter(venue).fetch_positions()
        assert [(p.market_id, p.side) for p in positions] == [(MARKET, PositionSide.LONG)]
        first, second = venue.sent("GET", "/v2/positions")
        assert first.url.params["user"] == WALLET and second.url.params["cursor"] == "abc"

    async def test_settlements_are_redemptions(self, venue):
        venue.on("GET", "/v2/activity", body={"data": [
            {"type": "REDEEM", "condition_id": CONDITION, "token_id": TOKEN, "size": 10, "usdc_size": 10, "timestamp": 1789650000},
            {"type": "REDEEM", "condition_id": CONDITION, "token_id": NO_TOKEN, "size": 4, "usdc_size": 0, "timestamp": 1789650000},
        ], "pagination": {"next_cursor": None}})
        won, lost = await adapter(venue).fetch_settlements()
        assert won.won is True and won.payout == D("10") and lost.won is False
        assert won.held == PositionSide.LONG and lost.held == PositionSide.SHORT and won.market_id == MARKET
        assert venue.sent("GET", "/v2/activity")[0].url.params["type"] == "REDEEM"

    async def test_fee_estimate_uses_the_clob_market_parameters(self, venue):
        venue.on("GET", f"/clob-markets/{CONDITION}", body={"t": [], "mts": 0.01, "mos": 5, "fd": {"r": 0.07, "e": 1, "to": True}})
        fee = await adapter(venue).fetch_fee_estimate(MARKET, Side.BUY, D("0.50"), D("100"))
        assert fee.taker_fee == D("1.75") and fee.maker_fee == 0

    async def test_heartbeat_adopts_the_expected_id(self, venue):
        venue.on("POST", "/v1/heartbeats", 400, {"error_msg": "Invalid Heartbeat ID", "heartbeat_id": "expected-1"})
        venue.on("POST", "/v1/heartbeats", 200, {"heartbeat_id": "next-2"})
        poly = adapter(venue)
        poly._heartbeat_id = "stale"
        assert await poly.send_heartbeat() == "next-2"
        bodies = [json.loads(r.content) for r in venue.sent("POST", "/v1/heartbeats")]
        assert bodies == [{"heartbeat_id": "stale"}, {"heartbeat_id": "expected-1"}]

    async def test_heartbeat_task_records_errors_and_stops(self, venue):
        venue.on("POST", "/v1/heartbeats", 500, {"error": "boom"})
        poly = adapter(venue)
        poly.start_heartbeat(interval_s=0.01)
        import asyncio
        await asyncio.sleep(0.05)
        assert poly.heartbeat_error is not None
        await poly.stop_heartbeat()
        assert poly._heartbeat_task is None

    async def test_approvals_through_the_relayer(self, venue):
        venue.on("GET", "/v1/account/transactions/params", body={"address": ADDRESS, "nonce": "12"})
        venue.on("POST", "/submit", body={"transactionID": "tx-1", "state": "STATE_NEW"})
        venue.on("GET", "/v1/account/transactions/tx-1", body={"transaction_id": "tx-1", "state": "STATE_MINED"})
        venue.on("GET", "/v1/account/transactions/tx-1", body={"transaction_id": "tx-1", "state": "STATE_CONFIRMED", "transaction_hash": "0xhash"})
        venue.on("GET", "/balance-allowance/update", body={})
        poly = adapter(venue, relayer_api_key="relayer-key", relayer_api_key_address=ADDRESS)
        result = await poly.execute_wallet_calls(sig.trading_approval_calls(), description="Set trading approvals", timeout_s=10, poll_interval_s=0)
        assert result["state"] == "STATE_CONFIRMED"
        submit = venue.sent("POST", "/submit")[0]
        assert submit.headers["RELAYER_API_KEY"] == "relayer-key"
        body = json.loads(submit.content)
        assert body["type"] == "WALLET" and body["to"] == sig.DEPOSIT_WALLET_FACTORY and body["nonce"] == "12"
        assert body["depositWalletParams"]["depositWallet"] == WALLET and len(body["depositWalletParams"]["calls"]) == 8
        typed = sig.wallet_batch_typed_data(WALLET, 12, int(body["depositWalletParams"]["deadline"]), body["depositWalletParams"]["calls"])
        assert EthAccount.recover_message(encode_typed_data(full_message=typed), signature=body["signature"]) == ADDRESS

    async def test_relayer_needs_its_key(self, venue):
        """Without Synpath's builder signer (unreachable here) and without a
        key of the account's own, there is no way to the relayer."""
        venue.on("GET", "/v1/account/transactions/params", body={"nonce": "0"})
        with pytest.raises(NotSupported, match="RELAYER_API_KEY"):
            await adapter(venue).redeem(CONDITION, neg_risk=False)
        assert not venue.sent("POST", "/submit")

    BUILDER = {"POLY_BUILDER_API_KEY": "bk", "POLY_BUILDER_TIMESTAMP": "1", "POLY_BUILDER_PASSPHRASE": "bp",
               "POLY_BUILDER_SIGNATURE": "bsig"}

    def relayer_routes(self, venue):
        venue.on("GET", "/v1/account/transactions/params", body={"nonce": "0"})
        venue.on("GET", "/v1/account/transactions/tx-9", body={"state": "STATE_CONFIRMED"})

    async def test_synpaths_builder_signer_needs_no_key_of_the_accounts_own(self, venue):
        self.relayer_routes(venue)
        venue.on("POST", "/v1/builder/sign", body={"headers": self.BUILDER})
        venue.on("POST", "/submit", body={"transactionID": "tx-9", "state": "STATE_NEW"})
        result = await adapter(venue).redeem(CONDITION, neg_risk=False)
        assert result["state"] == "STATE_CONFIRMED"
        submit = venue.sent("POST", "/submit")[0]
        assert submit.headers["POLY_BUILDER_SIGNATURE"] == "bsig" and "RELAYER_API_KEY" not in submit.headers
        asked = [json.loads(r.content) for r in venue.sent("POST", "/v1/builder/sign")]
        assert asked[-1] == {"method": "POST", "path": "/submit", "body": submit.content.decode()}, \
            "the signer signs the exact text that is sent"

    async def test_a_refused_builder_falls_back_to_the_accounts_own_key(self, venue):
        self.relayer_routes(venue)
        venue.on("POST", "/v1/builder/sign", body={"headers": self.BUILDER})
        venue.on("POST", "/submit", 401, {"error": "invalid authorization"})
        venue.on("POST", "/submit", body={"transactionID": "tx-9", "state": "STATE_NEW"})
        poly = adapter(venue, relayer_api_key="own", relayer_api_key_address=ADDRESS)
        await poly.redeem(CONDITION, neg_risk=False)
        submits = venue.sent("POST", "/submit")
        assert submits[0].headers["POLY_BUILDER_SIGNATURE"] == "bsig"
        assert submits[-1].headers["RELAYER_API_KEY"] == "own"

    async def test_a_declining_signer_says_why(self, venue):
        self.relayer_routes(venue)
        venue.on("POST", "/v1/builder/sign", 429, {"detail": "Synpath's daily relayer quota is used up"})
        with pytest.raises(NotSupported, match="quota is used up"):
            await adapter(venue).redeem(CONDITION, neg_risk=False)

    async def test_the_signer_can_be_turned_off(self, venue, monkeypatch):
        monkeypatch.setenv("SYNPATH_BUILDER_SIGNER_URL", "none")
        self.relayer_routes(venue)
        venue.on("POST", "/submit", body={"transactionID": "tx-9", "state": "STATE_NEW"})
        await adapter(venue, relayer_api_key="own", relayer_api_key_address=ADDRESS).redeem(CONDITION, neg_risk=False)
        assert not venue.sent("POST", "/v1/builder/sign")
        assert venue.sent("POST", "/submit")[0].headers["RELAYER_API_KEY"] == "own"

    async def test_relayed_failure_raises(self, venue):
        venue.on("GET", "/v1/account/transactions/params", body={"nonce": "0"})
        venue.on("POST", "/submit", body={"transactionID": "tx-2", "state": "STATE_NEW"})
        venue.on("GET", "/v1/account/transactions/tx-2", body={"state": "STATE_FAILED", "error_msg": "execution reverted"})
        poly = adapter(venue, relayer_api_key="k", relayer_api_key_address=ADDRESS)
        with pytest.raises(OrderRejected, match="reverted"):
            await poly.split(CONDITION, D("5"), neg_risk=True)
        call = json.loads(venue.sent("POST", "/submit")[0].content)["depositWalletParams"]["calls"][0]
        assert call["target"] == sig.NEG_RISK_CTF_COLLATERAL_ADAPTER and call["data"].startswith("0x72ce4275")

    async def test_legacy_wallets_cannot_send_transactions(self, venue):
        with pytest.raises(NotSupported, match="legacy"):
            await adapter(venue, signature_type=1).merge(CONDITION, D("1"), neg_risk=False)

    async def test_eoa_sends_signed_polygon_transactions(self, venue):
        rpc_calls = []

        def rpc(request: httpx.Request) -> httpx.Response:
            payload = json.loads(request.content)
            rpc_calls.append(payload)
            method = payload["method"]
            result = {
                "eth_getTransactionCount": "0x5", "eth_gasPrice": "0x3b9aca00", "eth_maxPriorityFeePerGas": "0x77359400",
                "eth_estimateGas": "0x186a0", "eth_sendRawTransaction": "0x" + "cd" * 32,
                "eth_getTransactionReceipt": {"status": "0x1", "transactionHash": "0x" + "cd" * 32},
            }[method]
            return httpx.Response(200, json={"jsonrpc": "2.0", "id": 1, "result": result})

        def route(request: httpx.Request) -> httpx.Response:
            return rpc(request) if request.url.host == "rpc.test" else venue.handler(request)

        poly = PolymarketTrading(
            creds(signature_type=0, funder=None, rpc_url="https://rpc.test/"),
            client=httpx.AsyncClient(transport=httpx.MockTransport(route)),
            limiter=BudgetLimiter(read_per_second=1000, write_per_second=1000),
        )
        result = await poly.redeem(CONDITION, neg_risk=False)
        assert result["receipts"][0]["status"] == "0x1"
        raw = next(c for c in rpc_calls if c["method"] == "eth_sendRawTransaction")["params"][0]
        tx = EthAccount.recover_transaction(raw)
        assert tx == ADDRESS

    async def test_eoa_needs_an_rpc(self, venue):
        with pytest.raises(NotSupported, match="RPC"):
            await adapter(venue, signature_type=0, funder=None).redeem(CONDITION, neg_risk=False)


class TestBuilderCode:
    """Synpath's builder code rides on every order unless the account sets its
    own or opts out; a refusal of the default code never stops trading."""

    ENV = {"POLYMARKET_PRIVATE_KEY": KEY, "POLYMARKET_SIGNATURE_TYPE": "3", "POLYMARKET_FUNDER": WALLET}

    @pytest.mark.parametrize("raw,expected", [
        (None, SYNPATH_BUILDER_CODE), ("", SYNPATH_BUILDER_CODE), ("none", None), ("NONE", None),
        ("0x" + "ab" * 32, "0x" + "ab" * 32),
    ])
    def test_the_environment_setting(self, raw, expected):
        env = dict(self.ENV, **({} if raw is None else {"POLYMARKET_BUILDER_CODE": raw}))
        assert load_polymarket(env).builder_code == expected

    def test_a_malformed_code_is_refused(self):
        with pytest.raises(CredentialsMissing, match="bytes32"):
            load_polymarket(dict(self.ENV, POLYMARKET_BUILDER_CODE="0x1234"))

    def test_opting_out_signs_no_builder(self):
        entry, _ = build(req(), builder_code=None)
        assert entry["order"]["builder"] == sig.ZERO_BYTES32

    ACCEPTED = {"success": True, "errorMsg": "", "orderID": "", "status": "live"}

    async def test_a_refused_default_code_is_dropped_and_the_order_resent(self, venue):
        venue.on("POST", "/order", 400, {"error": "invalid builder code"})
        venue.on("POST", "/order", body=self.ACCEPTED)
        venue.on("POST", "/order", body=self.ACCEPTED)
        poly = adapter(venue)
        order = await poly.create_order(req())
        assert order.status == OrderStatus.OPEN
        await poly.create_order(req())
        builders = [json.loads(r.content)["order"]["builder"] for r in venue.sent("POST", "/order")]
        assert builders == [SYNPATH_BUILDER_CODE, sig.ZERO_BYTES32, sig.ZERO_BYTES32]

    async def test_an_accounts_own_code_is_not_dropped(self, venue):
        venue.on("POST", "/order", 400, {"error": "invalid builder code"})
        with pytest.raises(OrderRejected, match="builder"):
            await adapter(venue, builder_code="0x" + "ab" * 32).create_order(req())
        assert len(venue.sent("POST", "/order")) == 1

    async def test_other_refusals_are_not_retried(self, venue):
        venue.on("POST", "/order", body={"success": False, "errorMsg": "not enough balance / allowance"})
        with pytest.raises(InsufficientFunds):
            await adapter(venue).create_order(req())
        assert len(venue.sent("POST", "/order")) == 1

    async def test_a_batch_resends_the_orders_refused_over_the_default_code(self, venue):
        venue.on("POST", "/orders", body=[self.ACCEPTED, {"success": False, "errorMsg": "builder code is disabled"}])
        venue.on("POST", "/orders", body=[self.ACCEPTED])
        results = await adapter(venue).create_orders([req(), req()])
        assert all(r.status == OrderStatus.OPEN for r in results)
        second = json.loads(venue.sent("POST", "/orders")[1].content)
        assert [e["order"]["builder"] for e in second] == [sig.ZERO_BYTES32]
